"""update post model

Revision ID: d73baafe9355
Revises: b107e77e1824
Create Date: 2026-09-19 22:21:56.788804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd73baafe9355'
down_revision: Union[str, Sequence[str], None] = 'b107e77e1824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'posts',
        sa.Column(
            'status',
            sa.Enum(
                'public',
                'private',
                'draft',
                name='poststatus'
            ),
            nullable=False,
            server_default='draft',
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'status')
    # ### end Alembic commands ###
